name: Release @jondotsoy/condition

on:
    push:
        branches:
            - develop

jobs:
    release:
        uses: ./.github/workflows/bun-release-package.yml
        permissions:
            contents: write
            pull-requests: write
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
