name: Publish page

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
        working-directory: packages/page
      - run: bun run build
        working-directory: packages/page
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
            path: packages/page/dist
